### ISSUE TITLE
one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!

### ISSUE THREAD

**Issue by Henry-Ding** [starskyzheng/panpop#11]
hi,
I create a new example, use my own data, name it the same as the example, and execute the command, and an error message appears:
![image](https://user-images.githubusercontent.com/56921882/222035214-7a4d6be5-509f-47ab-8dce-5e6fa93482ce.png)
Why does this error occur? What am I supposed to do? Looking forward to your reply.
best wishes,
henry

**Comment by starskyzheng** [comment]
Can you provide the log file `logs/5.1.mrege.log`?

**Comment by starskyzheng** [comment]
Also, Does the GFA file you used has 'P' line? This line must exists because it contains the chromosome information.

**Comment by Henry-Ding** [comment]
hi,
Sorry for the late reply.
![image](https://user-images.githubusercontent.com/56921882/224027894-0dfcd86f-a4e1-4477-80fe-f546bd9e5e22.png)
this is my 5.1.mrege.log.
And, My GFA is generated with `vg construct -r $ref -v $vars `, how do I check if GFA has 'P' line?
best wishes,
henry

**Comment by starskyzheng** [comment]
The GFA file should be a text file, which could be read easily. You can check `P` line by using `grep '^P' XX.gfa | less`.

`vg construct` will generated a vg format output by default, so I think this might be the problem. You can convert vg format to gfa format by `vg view --gfa --vg-in xx.vg`
