### ISSUE TITLE
PART stand alone clarification

### ISSUE THREAD

**Issue by Riccardo1274** [starskyzheng/panpop#15]
Dear Zeyu Zheng,
thank you for developing such a good merging tool.
I am trying to use the PART stand alone to first merge between different variant callers but same sample, and later to merge the output vcfs from this first part to get a multi-sample vcf.
From your paper, 'The PART method is applied twice to merge SVs from different callers, either for individual analysis or for multiple individuals within large populations'. I cannot find a way to input more than one vcf to the stand alone PART.
I looked at your example on Ocean, and here it seems to me that you have provided an already merged (with bcftools merge) vcf file. So, I guess I should merge different samples with bcftools merge, but how do I merge between different variant callers and same sample? How do you suggest to proceed?
Thanks in advance.
Kind regards,
Riccardo Rossi

**Comment by starskyzheng** [comment]
Hi, Rossi. 
Ths input file of "PART stand alone mode" must be one VCF file with multiple samples.
  If multiple VCF needs to be processed, such as from "different variant callers but same sample", you need to merge all those VCFs into one VCF file firstly. Each samples in this VCFs represents result of one variant callers. This process can be done by using `bcftools merge -m none -o OUT.vcf.gz IN1.vcf.gz IN2.vcf.gz ...`. Noted that the parameter of `-m none` is necessary to avoid the extra process of bcftools.
If you need to merge mulitple samles with mulitple variant callers, you need to merge variant callers for each samples separately. Then, you can merge SVs of multiple samples.

**Comment by Riccardo1274** [comment]
Thank you very much

**Comment by Wangping9** [comment]
Dear Dr. Zheng,
I have a question regarding merging SV files from different software sources. It is mentioned that we can first use bcftools to merge the files into one VCF and then use the PART script for further processing. However, I am unclear about how to select and retain only the SVs that are common to multiple software tools.
For example, I would like to retain only the SVs that are found in at least two different software tools, similar to the functionality provided by the SURVIVOR tool. Could you please help clarify how this can be achieved with PART?
Thank you in advance for your assistance!
Best regards,
xiaoping

**Comment by starskyzheng** [comment]
VCF should be in standard format, which the ALT must be bases, not `<INS>` or `<DEL>`. You may use `long_caller_parser.pl`.

**Comment by Zhenhua-Yan-one** [comment]
Dear Dr. Zheng,
when running the "PART stand alone mode", the VCF files need to be normalized. Does long_caller_parser.pl support the normalization of SV files generated by second‑generation sequencing callers such as GRIDSS, Manta, Delly, and Smoove?
Zhenhua   Yan
