### ISSUE TITLE
NGS数据 群体水平的SV检测，能否使用单一基因组作为reference？

### ISSUE THREAD

**Issue by bijinpeng** [starskyzheng/panpop#20]
我想对NGS数据进行群call sv，但目前并没有一种完善的群call 方法或软件。请问Panpop 能否用于单一基因组（fa格式)作为reference来进行sv的群call？

**Comment by starskyzheng** [comment]
使用NGS数据的前提是有一个SV集（再构成图基因组），而这个SV集通常由TGS测序得到。如果只有NGS数据和一个参考基因组，是没法用PanPop进行SV分析的。
PanPop的NGS流程是基于VG软件包的，本质上还是SV召回。只不过我们使用了其`augment`模式，可以对召回的SV进行一定修饰。
