### ISSUE TITLE
基于图形基因组的VCF合并

### ISSUE THREAD

**Issue by HaoWangLYL** [starskyzheng/panpop#28]
郑博士，您好
     我想请教一下，对于使用NGS数据利用giraffe基于图形基因组得到的SVs的VCF文件，是否可以使用panpop进行个体VCF文件的合并了，如果可以具体的应该是那一步了？并且这时候使用的ref.fa是指的构建图基因组时候使用的线性ref吗？

感谢！

**Comment by starskyzheng** [comment]
对于普通的线性基因组的VCF合并，您可以参考`https://github.com/starskyzheng/panpop/issues/15#issuecomment-1932548662`
使用VG和图基因组得到的VCF进行PART合并，需要是普通的线性基因组的才行，使用线性ref.fa即可。
如果VCF是特殊的非线性基因组的，则可能无法直接应用`bin/PART_run.pl`

**Comment by HaoWangLYL** [comment]
我们的VCF文件是使用VG 比对到minigraph_cactus构建的图基因组得到的

**Comment by starskyzheng** [comment]
您看看你的vcf文件第一列的染色体名字，是不是都能对应到线性基因组？

**Comment by HaoWangLYL** [comment]
嗯嗯，是这样的！感谢您的解惑！
&nbsp;


635169288
***@***.***



&nbsp;

**Comment by jinhua2024** [comment]
> 我们的VCF文件是使用VG 比对到minigraph_cactus构建的图基因组得到的

郑老师，您好！我是一个家系罕见病例5个个体的的图形基因组，使用minigraph_cactus构建的得到的。同时运行minigraph_cactus管道输出一个VCF文件，里边包含5个个体的变异信息。
首先，我想对这个vcf文件是筛选，按照家系遗传模式比如隐性遗传筛选候选SV变异。接着，把候选SV变异在其他二代测序的散发病例或家系病例或正常个体中进行SV基因分型，寻找患者特有的SV变异。我的这个情况，在SV基因分型时能够使用panpop的bin/PART_run.pl？输入的数据是不是我的候选SV变异文件、NGS数据、图基因组？
感谢您！！
