### ISSUE TITLE
PART合并个体SV

### ISSUE THREAD

**Issue by HaoWangLYL** [starskyzheng/panpop#29]
郑博士，您好！
     我在用part处理bcftoold合并的vcf文件时，按照您在CGM报告中的命令进行两轮合并，但最终的3.final.vcf.gz文件中只剩下了一条染色体的信息，然后我检查了其他文件，发现在第一轮的final中变只剩下了一条。
请问您知道这个是什么原因造成的了，应该如何处理了？

**Comment by starskyzheng** [comment]
可能原因太多了，请您检查一下下列信息吧。或者将数据上传一下看看。
fasta文件是否含有所有染色体信息？
运行中是否有报错？
从哪一步开始出现只剩一条染色体的？
只跑另一条染色体是否能出来结果？
