### ISSUE TITLE
KeyError in Snakefile_TGS , line 23

### ISSUE THREAD

**Issue by sd880131** [starskyzheng/panpop#30]
hi，when i try to use this software like  “snakemake -j 3 --reason --printshellcmds -s Snakefile_TGS”  ，then I got an error ：
KeyError in Snakefile_TGS , line 23：
'MIN_SUPPORT_CALLER_WITH_ASSB'

**Comment by starskyzheng** [comment]
Please update git repository and try again.
This was happend in old version of PanPop. (#22)
