### ISSUE TITLE
Could this pipeline run with assembled genome file only? without the reads file.

### ISSUE THREAD

**Issue by kmosi0** [starskyzheng/panpop#33]
I have the many assembled genome file, without the reads file. Could this pipeline support assembled genome file only? Thank you!

**Comment by starskyzheng** [comment]
Sorry. PanPop pipeline Not support this yet.
You can use run_PART.pl to combine vcfs generated by svim-asm. Noted a pre-process is needed: `perl scripts/long_caller_parser.pl --in {input.vcf} --out - --out_inv {output.inv_bed} --ref {input.ref} 2>>{log} | {BCFTOOLS} sort -O z -o {output.vcf}`

**Comment by kmosi0** [comment]
OK, thank you very much!
