### ISSUE TITLE
Error: cannot write to /tmp/bcftools.OL73yV/00024.bcf

### ISSUE THREAD

**Issue by polchan** [starskyzheng/panpop#37]
Hello! zheng

I encountered some issue while utilizing PART_run.pl. I utilized my custom-prepared VCF file, derived from aligning NGS data against the pan-genome using VG. I think it is achieve a workflow akin to your NGSpipeline. When I run this command using `perl  ~/tools/panpop/bin/PART_run.pl --in_vcf ./merge_bcftools.vcf.gz --outdir OUTDIR_RUN1 --ref_fasta_file ~/data/genome_data/malus/MdOrin.fa --threads 25 --tmpdir ./tmp`, it prompts me with the following error: 

> bcftools sort OUTDIR_RUN1/1.realign0.unsorted.vcf.gz -o OUTDIR_RUN1/1.realign0.sorted.vcf.gz
Writing to /tmp/bcftools.OL73yV
[buf_flush] Error: cannot write to /tmp/bcftools.OL73yV/00024.bcf
Cleaning
Mon Apr  8 23:27:51 CST 2024
perl /ngsproject/bcguo/tools/panpop-main/bin/../scripts/merge_similar_allele.pl --type 3 --invcf OUTDIR_RUN1/1.realign0.sorted.vcf.gz --outvcf OUTDIR_RUN1/2.thin1.unsorted.vcf.gz --sv2pav_merge_identity_threshold 0.6 --sv2pav_merge_diff_threshold 40 --threads 16  --tmpdir ./tmp 2>&1 | tee OUTDIR_RUN1/2.thin1.unsorted.vcf.gz.log
OUTDIR_RUN1/1.realign0.sorted.vcf.gz not exists!  at /ngsproject/bcguo/tools/panpop-main/scripts/../lib/zzIO.pm line 57.
        zzIO::open_in_fh("OUTDIR_RUN1/1.realign0.sorted.vcf.gz") called at /ngsproject/bcguo/tools/panpop-main/bin/../scripts/merge_similar_allele.pl line 102
Mon Apr  8 23:27:51 CST 2024
bcftools sort OUTDIR_RUN1/2.thin1.unsorted.vcf.gz -o OUTDIR_RUN1/2.thin1.sorted.vcf.gz
Writing to /tmp/bcftools.ebuema
[E::hts_open_format] Failed to open file "OUTDIR_RUN1/2.thin1.unsorted.vcf.gz" : No such file or directory
Could not read OUTDIR_RUN1/2.thin1.unsorted.vcf.gz
Cleaning
Mon Apr  8 23:27:51 CST 2024
perl /ngsproject/bcguo/tools/panpop-main/bin/../scripts/sv2pav.pl --invcf OUTDIR_RUN1/2.thin1.sorted.vcf.gz --outvcf OUTDIR_RUN1/2.thin2.unsorted.vcf.gz --enable_norm_alle 1 --max_len_tomerge 20 --sv_min_dp 40 --threads 16 2>&1 | tee OUTDIR_RUN1/2.thin2.unsorted.vcf.gz.log
OUTDIR_RUN1/2.thin1.sorted.vcf.gz not exists!  at /ngsproject/bcguo/tools/panpop-main/scripts/../lib/zzIO.pm line 57.
        zzIO::open_in_fh("OUTDIR_RUN1/2.thin1.sorted.vcf.gz") called at /ngsproject/bcguo/tools/panpop-main/bin/../scripts/sv2pav.pl line 102
Mon Apr  8 23:27:51 CST 2024
bcftools sort OUTDIR_RUN1/2.thin2.unsorted.vcf.gz -o OUTDIR_RUN1/2.thin2.sorted.vcf.gz
Writing to /tmp/bcftools.9f2NUo
[E::hts_open_format] Failed to open file "OUTDIR_RUN1/2.thin2.unsorted.vcf.gz" : No such file or directory
Could not read OUTDIR_RUN1/2.thin2.unsorted.vcf.gz
Cleaning
Mon Apr  8 23:27:51 CST 2024
ln -s 2.thin2.sorted.vcf.gz OUTDIR_RUN1/3.final.vcf.gz

So I hope you can help me solve this issue, if possible!

Thanks!

Best-wish!

Bo-cheng

**Comment by starskyzheng** [comment]
Please try this branch: `https://github.com/starskyzheng/panpop/tree/starskyzheng-patch-2`
I did not tested this branch yet. Your feedback is welcome!

**Comment by polchan** [comment]
Thanks!
I will give it a try later.

**Comment by starskyzheng** [comment]
What were the CHR column of the vcf file `OUTDIR_RUN1/3.final.vcf.gz `?

**Comment by polchan** [comment]
hello!
this is the first few lines of  `OUTDIR_RUN1/3.final.vcf.gz`  
[header.vcf.txt](https://github.com/starskyzheng/panpop/files/14986516/header.vcf.txt)

**Comment by starskyzheng** [comment]
Please also provides ref.fa file: `MdOrin.fa`

**Comment by polchan** [comment]
Good news! It seems that I have successfully run all the processes of `PART_run.pl.` However, I still have a question. The `merge_bcftools.vcf.gz` file I initially inputted was 130 Gb, but the final output file `3.final.vcf.gz` is only 1.9 Gb. Is this size reduction reasonable? In what form does the remaining 120+ Gb of data exist?

**Comment by starskyzheng** [comment]
I don't know. You must check by yourself.
If you have any result please let me know.

**Comment by polchan** [comment]
Alright! I have reviewed the previous vcf files and the new vcf files after merging. The former vcf files had over 20,000,000 variations, while the merged vcf file has more than 9,400,000 variations. I believe the main reason for the reduction is not the decrease in the number of variations, but rather that the descriptions of variations within individual samples were not retained during the merging process. Of course, these descriptions do not affect subsequent analyses.

this is a smaple of previous vcf: 
[previous.vcf.txt](https://github.com/starskyzheng/panpop/files/15019296/previous.vcf.txt)

this is a smaple of new vcf: 
[new.vcf.txt](https://github.com/starskyzheng/panpop/files/15019298/new.vcf.txt)

Thank you very much for the excellent software you have developed and the help you have provided recently!
