### ISSUE TITLE
No output result, and keeps showing "Nothing to be done Building DAG of jobs..."

### ISSUE THREAD

**Issue by fcbayern31** [starskyzheng/panpop#38]
Hello Dr. Zheng,

When I run NGS data using

 `snakemake -j 40 --reason --printshellcmds -s config.NGS.yaml` , 

it always shows
>  "Nothing to be done.
> Building DAG of jobs...
> Nothing to be done (all requested files are present and up to date). ”

The same happens when running the example NGS workflow:

> Building DAG of jobs...
> Nothing to be done (all requested files are present and up to date).
> Complete log: ../../.snakemake/log/2024-04-09T163028.914719.snakemake.log

I haven't found any other errors. 
What could be the reason for this?

**Comment by starskyzheng** [comment]
Can you list files in your `workdir`?

**Comment by fcbayern31** [comment]
Here are files in my workdir:

> Ref.gfa ##softlink
> sample.reads.list  ##softlink
> ASX-1.2.fq.gz ##softlink
> ASX-1.1.fq.gz ##softlink
> JPN_DS.1.fq.gz ##softlink
> JPN_DS.2.fq.gz ##softlink
> ...  

Below is my sample.reads.list(The separator is a space):

> ASX-1 ASX-1.1.fq.gz ASX-1.2.fq.gz
> JPN_DS JPN_DS.1.fq.gz JPN_DS.2.fq.gz
> ...

Below is my config.NGS.yaml:

> #################### Basic Parameters ####################
> ## Absolute paths are recommended for workdir and sample_reads_list_file
> # workdir: Dir contains sample_read.list and will store result files.
> workdir: "/home/***/panpop"
> # sample_reads_list_file: File name of sample_read.list. Must located in wirkdir.
> sample_reads_list_file: "sample.reads.list"
> # split_chr: (False or True). Weather split by chromosome for parallel running. This is useful for multi-node clster. This option can greatly reduce the memory usage in augment mode. If you only own one computer-node the recommended setting is False. Default is True.
> split_chr: True
> # mode: (genotype or augment). `genotype` mode will genotype SVs in the graph-genome. `augment` mode will extract novel SNPs and SVs for each sample. Default is `augment`.
> mode: "genotype"
> # Graph-based reference should be renamed as `Ref.gfa` and then placed in `workdir`. This value is not recommand for modifing! Default is `Ref`.
> graph: 'Ref'
> 
> 
> #################### More parameters ####################
> # mapper: can be either 'map' or 'gaffe', Default id `gaffe`
> mapper: 'gaffe'


And the result was : 

> Building DAG of jobs...
> Nothing to be done (all requested files are present and up to date).
> Complete log: ../.snakemake/log/2024-04-10T084544.593329.snakemake.log

I got same result running example in example/example_short_reads.

**Comment by fcbayern31** [comment]
Here are files in my workdir:

> Ref.gfa ##softlink
> sample.reads.list  ##softlink
> ASX-1.2.fq.gz ##softlink
> ASX-1.1.fq.gz ##softlink
> JPN_DS.1.fq.gz ##softlink
> JPN_DS.2.fq.gz ##softlink
> ...  

Below is my sample.reads.list(The separator is a space):

> ASX-1 ASX-1.1.fq.gz ASX-1.2.fq.gz
> JPN_DS JPN_DS.1.fq.gz JPN_DS.2.fq.gz
> ...
> 

Below is my config.NGS.yaml:

```
workdir: "/home/***/panpop"
sample_reads_list_file: "sample.reads.list"
Default is True.
split_chr: True
mode: "genotype"
graph: 'Ref'
mapper: 'gaffe'

```

And the result was : 

> Building DAG of jobs...
> Nothing to be done (all requested files are present and up to date).
> Complete log: ../.snakemake/log/2024-04-10T084544.593329.snakemake.log

I got same result running example in example/example_short_reads.

**Comment by starskyzheng** [comment]
May be a full file list of `workdir` will helps.
Was there exists some dirs?

**Comment by fcbayern31** [comment]
Thank you!
I have solved the problem. 
It was caused by the incorrect `snakefile`.
