### ISSUE TITLE
I have two type reads, HIFI reads and CLR reads, how to use them for SV calling.

### ISSUE THREAD

**Issue by kmosi0** [starskyzheng/panpop#40]
I have two type reads, HIFI reads and CLR reads, how to use them for SV calling. Merge them to one file to calling SV or calling SV respectively and merge vcf file ?  which one is better ? hope for you reply, thank you !

**Comment by starskyzheng** [comment]
HiFi reads is more accurately for SV calling. I recommend to use HiFi reads only.
If you need to use both two types of reads, you must separate two type of reads into two samples, and then calling SVs for each samples separately.
