### ISSUE TITLE
nucmer

### ISSUE THREAD

**Issue by pengyan19** [starskyzheng/panpop#41]
你好，我用软件的环境按照的nucmer，运行报错，看起来是版本低了，没有-t参数，请问该怎么配置高版本的nucmer?

Unknown option: t

  USAGE: nucmer  [options]  <Reference>  <Query>
    
Try '/public/home/pengyan/anaconda3/envs/panpop/bin/nucmer -h' for more information.

**Comment by starskyzheng** [comment]
是哪步出错的？

**Comment by pengyan19** [comment]
你好，是这个哈
Error in rule Assemblytics1nucmer:
    jobid: 354
    input: OS-1.fa, /public/home/pengyan/biosoft/panpop/panpop-starskyzheng-patch-1/example/ACB/of-5.fa
    output: 03_vcf/05_Assemblytics/of-5/1.nucmer.delta, 03_vcf/05_Assemblytics/of-5
    log: logs/2.of-5.Assemblytics.1.nucmer.log (check log file(s) for error details)
    shell:
        
        mkdir -p 03_vcf/05_Assemblytics/of-5
        /public/home/pengyan/anaconda3/envs/panpop/bin/nucmer --maxmatch -c 500 -b 500 -l 100 -t 10 OS-1.fa /public/home/pengyan/biosoft/panpop/panpop-starskyzheng-patch-1/example/ACB/of-5.fa --prefix 03_vcf/05_Assemblytics/of-5/1.nucmer >logs/2.of-5.Assemblytics.1.nucmer.log 2>&1
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Removing output files of failed job Assemblytics1nucmer since they might be corrupted:
03_vcf/05_Assemblytics/of-5
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: ../../.snakemake/log/2024-04-12T152510.828358.snakemake.log

**Comment by starskyzheng** [comment]
确实是版本不合适。
您方便吧`subworkflows/callSV3.py`文件的第250行改一下么？吧`-t {threads}`这个参数删掉，再试试

**Comment by starskyzheng** [comment]
另外呀，Assemblytics的准确性我评估过，很低，不建议用，建议用svim-asm

**Comment by pengyan19** [comment]
哦哦，好呢，svim-asm用到nucmer吗

**Comment by starskyzheng** [comment]
用不到的
