### ISSUE TITLE
YAML Error: Expected separator '---' #40

### ISSUE THREAD

**Issue by zwj426** [starskyzheng/panpop#42]
Dear @starskyzheng,
I encountered a problem while using panpop, which was caused by an error in YAML/Loader. pm, resulting in the inability to correctly recognize parameters. May I ask if there is any way to solve it? Thanks!

perl $path/PART_run.pl -i 06.merge_samples.chr4.vcf -o ./test -r Ref.fa -t 2 --force --tmpdir ./tmp
YAML Error: Expected separator '---'
Code: YAML_PARSE_ERR_NO_SEPARATOR
Line: 1
Document: 2
at ~/lib/YAML/Loader.pm line 88.

**Comment by starskyzheng** [comment]
Did you changed config files?

**Comment by zwj426** [comment]
Thank you for your reply. I didn't make any changes. I downloaded through ‘git clone https://github.com/StarSkyZheng/panpop.git’ and encountered the same error in both window and shell.

**Comment by starskyzheng** [comment]
Did you install PanPop using conda?

**Comment by zwj426** [comment]
I have tried to install it using conda, but unfortunately, I cannot find any tools related to PanPop in the virtual environment, such as 'PART_run.pl'.

conda env create -f conda.panpop.yaml
conda activate panpop
conda install -c bioconda svim-asm
cpanm MCE::Channel Tie::CharArray

**Comment by starskyzheng** [comment]
You should run `Part_run.pl` which downloaded from `https://github.com/StarSkyZheng/panpop.git` in our conda env.

**Comment by zwj426** [comment]
Thanks again for your reply. I resolved the issues above and then successfully ran the case. However, when running my own data, I ran into some problems that others have had before, but I have absolutely no idea how to fix it, can you give me some advice. Here is my input file which merged SVs via `bcftools concat merge`.  I would appreciate your [help!]

Duplicate specification "e|ext_bp_min=i" for option "e"
Now reading ref fasta :
Done reading ref fasta read 1958 contig / total 2770686120 bp
Warn! aln software(muscle) exit status(2)! redo! No. 1
Warn! aln software(muscle) exit status(2)! redo! No. 1
Warn! aln software(muscle) exit status(2)! redo! No. 1
Warn! aln software(muscle) exit status(2)! redo! No. 1
[Uploading chr27.ref.fna.gz…]()

**Comment by zwj426** [comment]
Thanks again for your reply. I resolved the issues above and then successfully ran the case. However, when running my own data, I ran into some problems that others have had before, but I have absolutely no idea how to fix it, can you give me some advice. Here is my input file which merged SVs via bcftools concat merge. I would appreciate your [help!]

Duplicate specification "e|ext_bp_min=i" for option "e"
Now reading ref fasta :
Done reading ref fasta read 1958 contig / total 2770686120 bp
Warn! aln software(muscle) exit status(2)! redo! No. 1
Warn! aln software(muscle) exit status(2)! redo! No. 1
Warn! aln software(muscle) exit status(2)! redo! No. 1
Warn! aln software(muscle) exit status(2)! redo! No. 1
[Uploading chr27.ref.fna.gz…]()

**Comment by zwj426** [comment]
[chr27.SVs2.vcf.gz](https://github.com/starskyzheng/panpop/files/15021884/chr27.SVs2.vcf.gz)

**Comment by zwj426** [comment]
Thanks again for your reply. I resolved the issues above and then successfully ran the case. However, when running my own data, I ran into some problems that others have had before, but I have absolutely no idea how to fix it, can you give me some advice. Here is my input file which merged SVs via bcftools concat merge. I would appreciate your [help!]

Duplicate specification "e|ext_bp_min=i" for option "e"
Now reading ref fasta :
Done reading ref fasta read 1958 contig / total 2770686120 bp
Warn! aln software(muscle) exit status(2)! redo! No. 1
Warn! aln software(muscle) exit status(2)! redo! No. 1
Warn! aln software(muscle) exit status(2)! redo! No. 1
Warn! aln software(muscle) exit status(2)! redo! No. 1
[Uploading data2.zip…]()

**Comment by starskyzheng** [comment]
Does the final result OK?

**Comment by starskyzheng** [comment]
The file `data2.zip` failed to upload.
So, Does the final result OK?

**Comment by zwj426** [comment]
No, it doesn't output any results. 
I re-uploaded the file, please try again.
[data2.zip](https://github.com/starskyzheng/panpop/files/15032819/data2.zip)

**Comment by starskyzheng** [comment]
Same a this issue（https://github.com/starskyzheng/panpop/issues/18#issuecomment-1959763266）
