### ISSUE TITLE
bcftools error

### ISSUE THREAD

**Issue by Flooooooooooooower** [starskyzheng/panpop#46]
您好郑博士！
我在使用panpop时遇到了以下报错，无法找到原因并解决问题。
希望能得到您的回复
![image](https://github.com/starskyzheng/panpop/assets/151424155/3bcbfddd-d526-460a-9912-b09de6f82bb9)

**Comment by starskyzheng** [comment]
log麻烦截个图

**Comment by Flooooooooooooower** [comment]
> log麻烦截个图

已经解决了，谢谢您及时回复！
