### ISSUE TITLE
我想知道Fill_DP.pl的用处

### ISSUE THREAD

**Issue by hanshenglei** [starskyzheng/panpop#48]
你好，郑博士！
        我有一个群体的sv文件，我想知道Fill_DP.pl在PART_run.pl之前运行还是在它之后运行，以及RADEME中你提到Fill_DP.pl仅添加深度信息，那该如何做后续处理，比如文中提到的软屏蔽；还是PART_run.pl运行完了之后再运行Fill_DP.pl就过滤完了
        期待您的回复
祝好！

**Comment by starskyzheng** [comment]
1. 先Fill_DP.pl，再PART_run.pl
2. 对的。具体参数可以看snakefile里写的，比如:
https://github.com/starskyzheng/panpop/blob/df6d0e72151d0456bf1bcccff6ad00ad27169f6f/subworkflows/panpopbase.py#L124

**Comment by starskyzheng** [comment]
> -r 和 -m_none 您好像没有解释清楚？

我加了一些说明  -r就是染色体 --m_none 就是跑bcftools merge时候的参数
不建议单独调用这个脚本
07ab3f15c44f70bc9e0b077f711229a9557f4cdc

>  2）merge_vcf_same_pos.pl这个脚本是用来解决以下情况吗：如果两个VCF文件中存在相同位置的变异记录，需要进行合并。这通常涉及到解决冲突，例如选择保留哪一个变异记录或者合并它们。 

不存在这种情况。这一步只是粗合并，只有当CHR、POS、ALT、REF都一样时候才会合并。

> 3）为什么flt_raw_vcfs.pl在example_short_reads/3.merge_rawvcf中4.filter_raw_vcf.1.vcf.gz使用了一次，此时还没有添加深度信息好像；6.aug_dp/之后才带有深度信息，并在7.aug_merge_rawvcf使用了flt_raw_vcfs.pl

将不准的位点删掉，可以减轻补全深度时候的计算量

4） 这是标准vcf格式，后续分析都可用。但是建议只保留二等位基因的SV

5）原本的VCF里只有突变个体的深度信息，补全的是参考基因型的个体的深度信息

6）见： https://github.com/starskyzheng/panpop/blob/07ab3f15c44f70bc9e0b077f711229a9557f4cdc/scripts/realign.pl#L637

7）panpop的这种方法处理inv容易不准确，所以inv是单独进行计算的。最后再合并

**Comment by starskyzheng** [comment]
1) DP信息在vcf头里，没有的话手动补上吧
` ##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">`

2) inv的分离是prase那步进行的。不用管了，inv反正也很少。

**Comment by starskyzheng** [comment]
1) INV建议作bed单独合并，用PART处理很可能不准确
2) 不需要了，因为所有位点都有深度信息了。

**Comment by starskyzheng** [comment]
不客气！没有更多问题我就关闭这个issue了。如果有更多问题请再新开一个issue
