### ISSUE TITLE
群体多个个体vcf合并

### ISSUE THREAD

**Issue by liweirfI** [starskyzheng/panpop#49]
您好！基于图形泛基因组，采用vg软件call程序，获得了2000多个个体vcf文件需要合并，对于survivor软件，使用./SURVIVOR merge sample_files 1000 2 1 1 0 30 sample_merged.vcf；对于panpop软件，请问是否使用./subworkflows/mergeSV3_pop.py脚本合并就可以？不需要额外执行./bin/PART_run.pl，对吗？

**Comment by starskyzheng** [comment]
`subworkflows/mergeSV3_pop.py`是snakemake脚本，无法直接运行。
只能使用`PART_run.pl`

**Comment by liweirfI** [comment]
非常感谢你的回复！
我大概流程：（1）采用vg软件call程序获得每个个体vcf文件，保留SV长度大于50 bp的vcf文件（较少服务器运算量，关注SV），采用bcftools merge -m none进行合并群体vcf文件；（2）参考https://doi.org/10.24433/CO.1577027.v1 中run流程， 采用PART_run.pl脚本，对合并后vcf文件进行处理。
存在问题：（1）针对图形泛基因组，PART_run.pl脚本中--ref_fasta_file选项，我使用骨架基因组（参考基因组），是否可以？（2）对于此群体SV合并流程，请问是否其他问题？请帮忙指出

**Comment by starskyzheng** [comment]
1. 需要vcf中的染色体在fasta中都存在就行
2. 理论上可行
3. 如果多等位基因SV较多，可以多运行几次PART_run.pl。理论上多等位基因SV会逐次减少
