### ISSUE TITLE
About panpop merge syri results

### ISSUE THREAD

**Issue by HW-Superior** [starskyzheng/panpop#50]
Hi zheng,
    I want to use panpop software to merge SV results of syri, and I want to know how to use --in_vcf to input the multiple vcf files in "~/panpop/bin/PART_run.pl --in_vcf *vcf -o output2 -r genome..fa --tmpdir tmp" command.

**Comment by starskyzheng** [comment]
see https://github.com/starskyzheng/panpop/issues/18#issuecomment-1959763266
