### ISSUE TITLE
使用PART模块后如何计算准确率和召回率？

### ISSUE THREAD

**Issue by zhengluo-lz** [starskyzheng/panpop#51]
郑博士您好！
当我们使用其他SV分型的软件对二代reads的群体进行SV分型后，再使用PART模块进行SV的合并，请问有好方法对合并后的准确率和召回率进行评估吗？

**Comment by zhengluo-lz** [comment]
> 您可以看我的NC文章，里面有写方法

我看文章里用的方法是Truvari的bench方法，使用的参数是 -p 50 -P 50 -r 500，但我看这个软件的参数说明Min sequence similarity. Set to 0 to ignore (0.7)和Min variant size similarity (0.7)的阈值范围应该是0-1吧，这个是文章里面写错了吗

**Comment by starskyzheng** [comment]
不好意思，确实写错了，是0.5
 `--pctsim 0.5 --pctsize 0.5 --refdist 500`
