### ISSUE TITLE
程序卡在pbsv检测sv的环节

### ISSUE THREAD

**Issue by cheninouc** [starskyzheng/panpop#52]
郑博士您好 ！@starskyzheng 
我在用TGS检测SV的时候，我使用了ont、CLR、ccs三种数据，其他几个变异检测软件都能顺利检测。当运行到pbsv的时候只生成了03_vcf/sample1/pbsv.svsig.gz这个文件，然后接下来4天依然在运行但没有任何新文件的产生。当我将pbsv流程从subworkflows/callSV3.py种屏蔽掉后重新运行TGS，可以顺利产生最终的vcf文件。我想问一下是否由于ont数据不适合pbsv的流程从而卡住了，还是需要对原始的fq.gz文件处理后才能进行TGS检测。
期待您的回复！

**Comment by starskyzheng** [comment]
ONT可以用pbsv的，我测试过。
这个卡住了，估计是pbsv出bug了。
少用一个sv-caller没啥问题的，可以不用pbsv

**Comment by HainanWu** [comment]
您好！我也遇到 pbsv 卡住的情况了，请问，您是在subworkflows/callSV3.py中如何屏蔽掉 pbsv相关进程的。

**Comment by starskyzheng** [comment]
https://github.com/starskyzheng/panpop/blob/e33e5938fb2647d614f9b55d3c1bcbd46b03ab4a/configs/config.TGS.yaml.def#L22

删掉pbsv就行

**Comment by HainanWu** [comment]
您好！
1. 我已经在 configs/config.TGS.yaml.def 将 pbsv 删除，只保留了 SV_CALLER_LIST: [sniffles, cuteSV, svim, Assemblytics, SVIM_asm] ，但是在 Job stats: 还是有 pbsv_call  pbsv_discovery 的任务。

![Image](https://github.com/user-attachments/assets/809d3f28-7ae0-4645-80b5-1f26728fb15b)

使用的 configs/config.TGS.yaml.def如下：

![Image](https://github.com/user-attachments/assets/245c487e-c73b-4620-8962-3ac0da40df0b)

2. 此外，我还尝试在  subworkflows/callSV3.py 中注释掉与pbsv相关的部分，Job stats: 已经没有了 pbsv_call  pbsv_discovery 的任务，但是，程序在正常运行1天后只完成了20 %的工作任务就结束了，过程中也没有任何报错，仅仅是单纯的类似于跑完任务（但实际仅仅只完成了20%的 Job ID）。callSV3.py中注释部分如下：
1）

![Image](https://github.com/user-attachments/assets/75b6128a-693b-42bc-aef5-d885c4268f2b)
2）

![Image](https://github.com/user-attachments/assets/6ac5221a-f0ab-4684-9c29-4d7367a742c7)

工作状态的Job stats:如下图：

![Image](https://github.com/user-attachments/assets/4c9a39ee-ae07-4771-94fc-9f96d6603fce)

![Image](https://github.com/user-attachments/assets/3c5e1cde-6ce3-41f0-908d-803bef1e3c61)

**Comment by starskyzheng** [comment]
`configs/config.TGS.yaml`
这个文件状态如何？

**Comment by HainanWu** [comment]
老师您好！
1. PanPop软件目录下为：

![Image](https://github.com/user-attachments/assets/deadc9fd-1522-4e3b-ac4a-dd8c5b3cabed)
configs的目录结构为：

![Image](https://github.com/user-attachments/assets/170c4e5f-ff19-42ce-945e-3ccc187e9471)

PonPop中的 example_long_reads 的测试数据是可以跑通的。但是在跑自己数据时，将pbsv从configs/config.TGS.yaml配置文件中删除时，pbsv的job ID还是存在，后续跑到 pbsv call 这步时就会出现卡死，四五天一直在进行这步。
2. 注释掉 pbsv 相关行，我发现之前 在注释时 callSV3.py脚本中，在 rule consensus_inv：部分，我忘记给 “perl {workflow.basedir}/scripts/long_inv_bed2vcf.pl --ref {input.ref} --out {output.vcf} --sample {params.sample} {input.bed1} {input.bed2} {input.bed3} >>{log} 2>&1” 这其中的{input.bed4} （与pbsv相关）给删除了。重新注释后的PanPop程序还在运行中，已完成任务的30%。

[panpop_在配置文件(SV_CALLER_LIST)删除pbsv的日志文件.log](https://github.com/user-attachments/files/20971549/panpop_.SV_CALLER_LIST.pbsv.log)
[Panpop_注释掉pbsv后的日志文件.log](https://github.com/user-attachments/files/20971550/Panpop_.pbsv.log)

**Comment by starskyzheng** [comment]
第一个，可能是旧文件夹的干扰，建议换个workdir再试试。可以用--dry-run来调试。
第二个，是不是内存占用太大被杀掉了？可以将stdout和stderr保存下来看看，就是`snakemake xxx >log 2>&1`

**Comment by HainanWu** [comment]
第二个，我发现是注释 callSV3.py脚本时，perl {workflow.basedir}/scripts/long_inv_bed2vcf.pl --ref {input.ref} --out {output.vcf} --sample {params.sample} {input.bed1} {input.bed2} {input.bed3} >>{log} 2>&1，中的{input.bed4}没删除，修改后，重新提交程序还在运行中，已经运行18个小时，完成了32%的任务。

第一个旧文件夹下可能有干扰，等会我再试试看呢。

**Comment by HainanWu** [comment]
老师您好！
我刚又对第一个您的建议又测试了下，在一个新文件夹下测试，“/home/train/wuhainan/01.Pangenome/10.SV_Pan_genome/02.panpop_SV_Pangenome”，summary of the DAG of jobs 中还是会出现 pbsv_call  pbsv_discovery的任务，日志文件如下：

[新建文件下日志文件.log](https://github.com/user-attachments/files/20972065/default.log)

**Comment by HainanWu** [comment]
提交的命令为：“snakemake -j 80 --dry-run -s Snakefile_TGS >run.log 2>&1”。
