### ISSUE TITLE
新开发的软件的SV的合并

### ISSUE THREAD

**Issue by Yangzhen-Li** [starskyzheng/panpop#53]
郑博士，您好！

非常棒的一个软件，正准备试一下。

请教个简单的问题，最近用2个比较新的SV callers, DeBreak 和dysgu 从二代和三代ONT测序数据中call SV了，应该可以用PanPop进行整合合并吧？

祝科研顺利！

谢谢

**Comment by starskyzheng** [comment]
见 https://github.com/starskyzheng/panpop/issues/18#issuecomment-1959763266
格式对就能用，否则要转成标准vcf格式。
issue里有方法，您翻一下
