### ISSUE TITLE
运行FILL_DP和PART之后的得到的结果解释

### ISSUE THREAD

**Issue by hanshenglei** [starskyzheng/panpop#58]
你好，郑博士，
       我想快速的知道最终split之后的sv文件中的ZORIPOS=XXX;ZORIEND=XXX;ZLEN=XXX，和某些样本中的./.是什么意思；我的自己的二代脚本为将DEL、DUP、INS的变异先进行单个样本多个caller的PART后进行merge_caller，然后再进行fill_dp和PART，得到的vcf文件与分离出来的INV进行baftools concat，得到的sv文件中ZORIPOS=XXX;ZORIEND=XXX;ZLEN=XXX和某些样本中的./.我并不知道是什么意思。看你在别的问题下回答对于sv要使用fill_dp.pl，但是我已经使用了。

祝好

**Comment by starskyzheng** [comment]
./.就是不知道这个位点是什么Genotype，也就是深度不足。
ZORIPOS和ZORIEND就是realign group的起始位置和终止位置。ZLEN是长度。一般没用。
拆allele和转双等位基因是通过PART算法。flt_vcf_maf_by_allele.pl是过滤MAF的。

**Comment by starskyzheng** [comment]
1. 是一样的
2. 去除了
