### ISSUE TITLE
处理二代数据报错

### ISSUE THREAD

**Issue by C-YONG** [starskyzheng/panpop#59]
郑博士 你好 ！
我在处理二代数据的时候出现报错  另外 二代数据call SV的基因组只能是graph-genome或者pan-genome吗？ 普通的基因组fasta文件是否可以？
![image](https://github.com/starskyzheng/panpop/assets/165139484/7449334c-0526-4858-b010-f14e9ec83250)

**Comment by starskyzheng** [comment]
不行，二代算是vg的召回，没有sv集没法算的。
