### ISSUE TITLE
希望保留Sv最后合并文件的info信息 例如svtype等

### ISSUE THREAD

**Issue by C-YONG** [starskyzheng/panpop#60]
郑博士 你好！
我使用THS进行了三代数据的SV分析，在合并多个软件多个个体后发现info信息被clean了，于是我修改了long_caller_parser.pl脚本，改为my $clear_info = 0; 随后进行了SV calling，但是在合并多个软件sv时出现了以下报错，是什么原因造成的？我如何得到保留sv info信息的05merge文件 
![image](https://github.com/starskyzheng/panpop/assets/165139484/8d6deec3-d8ba-4be6-8f45-dd0b8efab98c)

**Comment by starskyzheng** [comment]
这个信息没用的。
如果实在想试试，您可以试试补全VCF头。

**Comment by C-YONG** [comment]
我们希望使用三代数据的SV来矫正二代数据。当我们使用dysgu软件来re-genotype二代数据时，软件需要info信息，因此我们希望我们得到的vcf文件具有info信息，能帮我们提供一下具体的做法嘛 非常感谢!

**Comment by starskyzheng** [comment]
```
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Length of the SV">
##INFO=<ID=STRAND,Number=1,Type=String,Description="Strands of supporting reads for structural variant">
##INFO=<ID=AF,Number=1,Type=Float,Description="Allele Frequency">
```
另外，我没用过dysgu软件。VCF格式比较灵活，info信息很可能不通用。
