### ISSUE TITLE
分型结果中的等位基因数量大于2

### ISSUE THREAD

**Issue by quanc1989** [starskyzheng/panpop#61]
您好，

想向您请教一下，分型结果中为什么会出现诸如2/2或0/3这样的结果，如何与传统分型结果的0/0 0/1 1/1相对应呢？

比如0/3应该认为是传统的杂合子还是纯合子呢？

非常感谢

**Comment by starskyzheng** [comment]
0/0  1/1  2/2都是纯合子;
0/1  0/2  1/2是杂合子;
这里的0 1 2是指基因型。具体请看vcf格式说明

**Comment by Johnsonzcode** [comment]
相同，利用PART分析了上游得到的vcf，结果中存在大于2的基因型，如下：GT      1/1     2/2     1/1     3/3     1/1     4/4     1/1     5/1     1/1     6/6     1/1     4/4     4/4     1/0     4/4     4/4     7/7     7/7     4/4     4/4     1/1     1/1     0/0     1/1     4/4     4/4     1/1     3/3     3/3     1/1     1/1     1/1     4/4     0/0     4/4     8/8     1/1     4/4     1/1     9/10    0/0     0/0     1/0     0/0     0/0     7/7     11/11   3/3     10/10   3/3     3/3     3/3     3/3     3/3     3/3     1/1     3/3     7/7     3/3     3/3     1/0     3/3     1/0     1/0     4/4     0/0     7/7     4/4     11/11   4/4     0/0     3/3     0/0     1/1     0/0     0/0     12/12   0/0     12/12   0/0     0/0     0/0     1/1     0/0     1/1     0/0     0/0     11/11   1/1     1/1     4/4     1/1     4/4     1/1     4/4     3/3     4/4     0/0     0/0     0/0     0/0     6/6     11/11   12/12   4/4     0/0     4/4     1/1     7/7     4/4     4/4     13/13 请问如何理解

**Comment by Johnsonzcode** [comment]
可以理解为这些位点是多等位基因位点吗

**Comment by quanc1989** [comment]
@Johnsonzcode 不同的数字代表不同的等位基因，所以大于1的就是多等位基因，我之前也没看懂

**Comment by Johnsonzcode** [comment]
> @Johnsonzcode 不同的数字代表不同的等位基因，所以大于1的就是多等位基因，我之前也没看懂

OK，谢谢
