### ISSUE TITLE
long_caller_parser.pl会删除几乎所有的DEL？

### ISSUE THREAD

**Issue by hui-liu** [starskyzheng/panpop#65]
用最新版的Sniffles2（v2.4）得到SV后，使用long_caller_parser.pl进行过滤，发现几乎所有的DEL都被删除，请问这是什么原因？

**Comment by starskyzheng** [comment]
请列举一个被删掉的DEL，把vcf的那一行贴出来看看

**Comment by hui-liu** [comment]
例如：
1       349925  Sniffles2.DEL.FE5S0     CGTTTCTGAAAGGCCCCGATCCGGACTGCCTAAAGTCCGGTCGAGAGAAGTCCTAGCCAACGATCCTATTGAGGATCGCGGGCGTTACA      C       60      PASS    PRECISE;SVTYPE=DEL;SVLEN=-88;END=350013;SUPPORT=38;COVERAGE=40,39,39,39,36;STRAND=+-;AF=0.974;STDEV_LEN=0.740;STDEV_POS=0.655  GT:GQ:DR:DV     1/1:60:1:38

**Comment by starskyzheng** [comment]
看起来没啥问题，源文件方便上传么？我重现一下试试

**Comment by hui-liu** [comment]
这是VCF文件：
[ERR11436632.vcf.gz](https://github.com/user-attachments/files/16201575/ERR11436632.vcf.gz)

参考基因组是拟南芥：https://www.arabidopsis.org/download/file?path=Sequences/Assemblies/TAIR9_chr_all.fas
