### ISSUE TITLE
The result of running PART.pl alone is empty

### ISSUE THREAD

**Issue by JiaB-He** [starskyzheng/panpop#66]
你好，郑博士
我从README说明看到可以单独运行PART.pl可以优化群体合并结果。并且参照你的CodeOcean流程说明PART.pl需要输入的是一个包含基因型的群体结果。我输入bcftools merge合并后的多样本SV VCF文件运行PART.pl，运行命令为perl PART_run.pl --in_vcf 10.sample.bcftools.vcf -o 10.sample.panpop.vcf-r refgenome.fa -t 36 --tmpdir TMPDIR &>log.panpop.txt &。但是运行结果只有VCF头部内容，没有变异记录。我想知道这是什么原因？
该压缩包上传了输入VCF文件和log记录
[panpop.zip](https://github.com/user-attachments/files/16323025/panpop.zip)

祝好

**Comment by starskyzheng** [comment]
挺奇怪的，您吧1|1换成1/1试试呢？

**Comment by JiaB-He** [comment]
可以运行了，谢谢！

**Comment by JiaB-He** [comment]
结果文件中有变异记录的第五列是*不知道是什么意思？是代表该变异位点的查询序列不确定吗？

**Comment by starskyzheng** [comment]
*就是deletion
