### ISSUE TITLE
Can PANPOP be used to combine individual VCF results?

### ISSUE THREAD

**Issue by vegetableyu** [starskyzheng/panpop#70]
郑博士您好，
        请问我call出每个样本各自的vcf后，PANPOP有合并所有个体的vcf得到最终合并的vcf的功能吗？
祝好

**Comment by starskyzheng** [comment]
当然。您可以试试`PART_run.pl`
https://github.com/starskyzheng/panpop?tab=readme-ov-file#s_example

**Comment by vegetableyu** [comment]
> 当然。您可以试试`PART_run.pl` https://github.com/starskyzheng/panpop?tab=readme-ov-file#s_example

请问执行perl panpop/bin/PART_run.pl --in_vcf INPUT.vcf -o OUTDIR_RUN1 -r REFERENCE.FASTA  -t 16 --tmpdir TMPDIR命令时输入的INPUT.vcf是所有样本合并后的vcf吗？请问这个vcf如何得到呢？

**Comment by starskyzheng** [comment]
可以参考这个
https://github.com/starskyzheng/panpop/issues/49#issuecomment-2111488560
