### ISSUE TITLE
panpop使用

### ISSUE THREAD

**Issue by sueddfy** [starskyzheng/panpop#72]
郑老师您好，最近我在合并结构变异的时候遇到了一点问题，想问一下使用panpop合并多个个体基于多种call-SV的软件进行合并，是按不同个体还是按不同软件进行合并呢？另外，我的测序数据是二代数据，在没有参考图基因组的情况下是否可以用panpop进行合并呢？（https://codeocean.com/capsule/9511278/tree/v1）这个网站中的PART-run.pl是只进行合并的流程吗？期待老师的回复，祝您中秋节快乐，身体健康！

**Comment by starskyzheng** [comment]
`是按不同个体还是按不同软件进行合并呢` 
都可以的。

`我的测序数据是二代数据，在没有参考图基因组的情况下是否可以用panpop进行合并呢？`
就用PART_run.pl即可，使用用线性的参考基因组。

另外，您可以仔细阅读readme和issues，以便理解和应用PanPop。
