### ISSUE TITLE
Not getting any results after merging VCFs

### ISSUE THREAD

**Issue by poddarharsh15** [starskyzheng/panpop#73]
Hi @starskyzheng 

I’m using PanPop under a Conda environment to merge structural variant (SV) VCF files. These VCF files had previously been merged using bcftools as I’m working with multiple samples. Unfortunately, I’m not getting any results after running the commands as outlined below.(only vcf headers in the vcf files)

Could you kindly provide some suggestions on how I might resolve this issue? I’m attaching my merged VCF files along with the code I used for reference.

1.` bcftools merge -m none -o bcftools.vcf.gz 140528_D00360_0018_AH8VC6ADXX.vcf.gz 140528_D00360_0019_BH8VDAADXX.vcf.gz 140605_D00360_0020_AH9V1RADXX.vcf.gz 140605_D00360_0021_BH9V1VADXX.vcf.gz 140609_D00360_0023_BH9UD5ADXX.vcf.gz`

2. 
```
perl ~/structural_varinats/panpop/panpop/bin/PART_run.pl --in_vcf bcftools.vcf.gz -o OUTDIR_RUN1 -r /home/tigem/h.poddar/short_reads_pipelines/ref_genome/GRCh38/GRCh38.primary_assembly.genome.fa -t 16 --tmpdir TMPDIR

perl ~/structural_varinats/panpop/panpop/bin/PART_run.pl --in_vcf OUTDIR_RUN1/3.final.vcf.gz -o OUTDIR_RUN2 -r /home/tigem/h.poddar/short_reads_pipelines/ref_genome/GRCh38/GRCh38.primary_assembly.genome.fa -t 16 --tmpdir TMPDIR -not_first_merge
```

Thank you in advance for your help!

> input

[bcftools.vcf.gz](https://github.com/user-attachments/files/17013678/bcftools.vcf.gz)
[truvari_merge.vcf.gz](https://github.com/user-attachments/files/17013680/truvari_merge.vcf.gz)

**Comment by starskyzheng** [comment]
https://github.com/starskyzheng/panpop?tab=readme-ov-file#standalone-entry-for-part
`Noted REF, ALT and GT (colunm 4, 5 and 9) need to be completed in the VCF file. (see https://github.com/starskyzheng/panpop/issues/18)`
