### ISSUE TITLE
panpop 安装

### ISSUE THREAD

**Issue by zgliu2000** [starskyzheng/panpop#75]
郑老师你好，我在Linux上使用conda进行安装panpop 时出现了报错，进行到这一步cpanm Tie::CharArray，显示Tie::CharArray is up to date. (1.00)请问是什么什么原因造成 ？应该怎么解决这个问题

**Comment by starskyzheng** [comment]
可以运行run_PART.pl试试，看看有报错么

**Comment by zgliu2000** [comment]
当我运行PART_run.pl&nbsp; 出现了下面的错误
Can't locate read_config.pm in @INC (you may need to install the read_config module) ***@***.*** contains: /ngsproject/zgliu/tools/panpop/bin/../lib /ngsproject/zgliu/miniforge-pypy3/lib/perl5/5.32/site_perl /ngsproject/zgliu/miniforge-pypy3/lib/perl5/site_perl /ngsproject/zgliu/miniforge-pypy3/lib/perl5/5.32/vendor_perl /ngsproject/zgliu/miniforge-pypy3/lib/perl5/vendor_perl /ngsproject/zgliu/miniforge-pypy3/lib/perl5/5.32/core_perl /ngsproject/zgliu/miniforge-pypy3/lib/perl5/core_perl .) at /ngsproject/zgliu/tools/panpop/bin/PART_run.pl line 33.
BEGIN failed--compilation aborted at /ngsproject/zgliu/tools/panpop/bin/PART_run.pl line 33.

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starskyzheng/panpop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月5日(星期六) 晚上10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [starskyzheng/panpop] panpop 安装 (Issue #75)





 
可以运行run_PART.pl试试，看看有报错么

**Comment by starskyzheng** [comment]
`/ngsproject/zgliu/tools/panpop/bin/../lib` 这文件夹里有啥？

**Comment by zgliu2000** [comment]
&nbsp;Identity.pm
-rw-rw-r-- 1 zgliu zgliu 4.7K Oct&nbsp; 6 11:45 prase_vcf.pm
-rw-rw-r-- 1 zgliu zgliu 2.4K Oct&nbsp; 6 11:45 read_config.pm
-rw-rw-r-- 1 zgliu zgliu&nbsp; 31K Oct&nbsp; 6 11:45 realign_alts.pm
-rw-rw-r-- 1 zgliu zgliu 7.4K Oct&nbsp; 6 11:45 zzBed.pm
-rw-rw-r-- 1 zgliu zgliu 2.3K Oct&nbsp; 6 11:45 zzIO.pm
-rw-rw-r-- 1 zgliu zgliu 7.8K Oct&nbsp; 6 11:45 zzmcl.pm





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starskyzheng/panpop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月6日(星期天) 下午2:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [starskyzheng/panpop] panpop 安装 (Issue #75)





 
/ngsproject/zgliu/tools/panpop/bin/../lib 这文件夹里有啥？

**Comment by zgliu2000** [comment]
现在又出现了新的错误Can't locate YAML.pm in @INC (you may need to install the YAML module) ***@***.*** contains: /ngsproject/zgliu/tools/panpop/bin/../lib /ngsproject/zgliu/miniforge-pypy3/envs/panpop/lib/perl5/5.32/site_perl /ngsproject/zgliu/miniforge-pypy3/envs/panpop/lib/perl5/site_perl /ngsproject/zgliu/miniforge-pypy3/envs/panpop/lib/perl5/5.32/vendor_perl /ngsproject/zgliu/miniforge-pypy3/envs/panpop/lib/perl5/vendor_perl /ngsproject/zgliu/miniforge-pypy3/envs/panpop/lib/perl5/5.32/core_perl /ngsproject/zgliu/miniforge-pypy3/envs/panpop/lib/perl5/core_perl .) at /ngsproject/zgliu/tools/panpop/bin/../lib/read_config.pm line 29.
BEGIN failed--compilation aborted at /ngsproject/zgliu/tools/panpop/bin/../lib/read_config.pm line 29.
Compilation failed in require at /ngsproject/zgliu/tools/panpop/bin/PART_run.pl line 33.
BEGIN failed--compilation aborted at /ngsproject/zgliu/tools/panpop/bin/PART_run.pl line 33.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starskyzheng/panpop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月6日(星期天) 下午2:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [starskyzheng/panpop] panpop 安装 (Issue #75)





 
/ngsproject/zgliu/tools/panpop/bin/../lib 这文件夹里有啥？
